### ISSUE TITLE
Issue when Username has Space

### ISSUE THREAD

**Issue by RuthlessRuler** [pbatard/Fido#11]
So My Username contains a space so when I'm using it along with Rufus it doesnt Work
Here's What Log has to say:

> Downloading https://github.com/pbatard/Fido/releases/download/v1.12/Fido.ps1.lzma
File length: 7.3 KB
Successfully downloaded 'Fido.ps1.lzma'
Signature is valid ✓
Processing -File 'C:\Users\Ruthless' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.
Windows PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.
Exited download script with code: -196608

**Comment by pbatard** [comment]
Thanks for reporting this. Looks like I forgot to quote a few paths when invoking the Fido script, so I'll make sure to fix that for the next version.
