### ISSUE TITLE
Feature request: CLI support

### ISSUE THREAD

**Issue by shawnkhall** [pbatard/Fido#15]
I understand that this is primarily for Rufus, but I'm in need of being able to directly download the appropriate ISOs from a command line to aid in command-line based Win10 upgrades on the active device. The CLI syntax should require the answers to each selection as an argument, or even assume the values for the current installation with optional overrides. 

Something like:

`powershell -ExecutionPolicy bypass .\Fido.ps1 -version 10 -release "20H1" -edition "home/pro" -locale "en-US" -architecture "x64"`

`powershell -ExecutionPolicy bypass .\Fido.ps1 -assumecurrent -release "1909" `

**Comment by pbatard** [comment]
I'll accept a patch if anyone is willing to contribute (that's the reason why the script is Open Source).

Otherwise, you may have to wait for a long time, as I'm only planning to add features that benefit Rufus at this stage, and I'm already struggling to find the time to do just that...
