### ISSUE TITLE
The following error occurs using the Fido script

### ISSUE THREAD

**Issue by dingpengyu** [pbatard/Fido#22]
The error message is as follows:
Error
 OK button 
Error: The response could not be parsed because the Internet Explorer engine is not available or the initial startup configuration of Internet Explorer is incomplete. Please specify the UseBasicParsing parameter and try again.
testing  message:
Microsoft Windows [version 10.0.19042.746]
Browser Information:
google chrome version 90.0.4412.5 dev （64 bit）
Microsoft Edge version 88.0.705.68 (64 bit)
Microsoft Edge version 90.0.789.1 dev (64 bit
thanks

**Comment by pbatard** [comment]
The script does requires Internet Explorer to be available on your platform.

If you don't have IE available, it cannot run.

**Comment by dingpengyu** [comment]
I have deleted Internet Explorer from my computer
