### ISSUE TITLE
Error：无法分析响应内容，因为 Internet Explorer引擎不可用，或者Internet Explore的首次启动配置不完整。请指定 Use BasicParsing参数，然后再试一次。

### ISSUE THREAD

**Issue by Zacharia2** [pbatard/Fido#23]
Error：无法分析响应内容，因为 Internet Explorer引擎不可用，或者Internet Explore的首次启动配置不完整。请指定 Use BasicParsing参数，然后再试一次。

**Comment by Zacharia2** [comment]
Windows规格

版本：Windows10家庭版
版本号：20H2
安装日期：2020/9/12
操作系统内部版本：19042.867
体验：Windows Feature experience pack 120.2212551.0

**Comment by pbatard** [comment]
Duplicate of #22.

Fido requires Internet Explorer to be installed to work. If you don't have Internet Explorer installed, it will not work.
