### ISSUE TITLE
Windows 7 - Other Editions/Versions

### ISSUE THREAD

**Issue by PaulNevada** [pbatard/Fido#28]
Hi, Author!
First of all - thank you very much for the tool!
Is it possible to expand the list of the images with all the other editions for Windows 7 and for any languages?

**Comment by pbatard** [comment]
Not unless one provides __public links__ that don't require the provision of a license key.

For now, [only 4 such links are known](https://github.com/pbatard/Fido/blob/2a139583ce0f547527d948e3ed8d663b4e074c1c/Fido.ps1#L298-L309), all for the English Professional and Home Premium versions, and that's the ones that are hardcoded in the application.

**Comment by PaulNevada** [comment]
Understood. Starred. Thanks!
