### ISSUE TITLE
Cannot download French Canadian or Chinese traditional

### ISSUE THREAD

**Issue by Evernow** [pbatard/Fido#29]
Hello there.

Attempting to download French Canadian and Chinese traditional ISOs, however it says invalid Windows language provided or it downloads the simplified version in the case of Chinese.

Options tried:

```
 -Lang "Chinese (Traditional)"
```

```
 -Lang Chinese (Traditional)
```

```
 -Lang "Chinese Traditional"
```

```
 -Lang "French Canada"
```

```
 -Lang FrenchCanadian
```

```
 -Lang "French (Canada)"
```

Download works through Rufus, not sure what the proper argument is, as a copy paste from what `-Lang List` provides does not work for this case (and I assume others like Spanish, which I haven't tested)

**Comment by mati97xdd** [comment]
-Lang is treated like a regex, you can match a part of the string:` -Lang Traditional` `-Lang Canadian` or you can escape brackets: `-Lang "Chinese \(Traditional\)"`.
Btw `-Lang "French Canadian"` works fine.

@pbatard If that's not the behavior you intended I could write a pull request.

**Comment by pbatard** [comment]
@mati97xdd, that makes sense indeed, though I expect that users of the script may not realise that parentheses will turn their option into a regex (but at the very least I do expect them to understand that they should use quotes if the parameter contains a space).

If you have a proposal on how we may be able to accept something like `"Chinese (Traditional)"` and get a match without escaping the parentheses, I think I'll be interested, if it's not too much trouble for you.
