### ISSUE TITLE
Running Fido.ps1 from URL as Scriptblock

### ISSUE THREAD

**Issue by couleurm** [pbatard/Fido#36]
##### just wanted to share this way of using Fido since I notice it's being compressed and shared in releases, feel free to add this to the readme,

The very last version of Fido can be ran by simply entering this command in PowerShell:

```powershell
Invoke-Expression (Invoke-RestMethod https://github.com/pbatard/Fido/raw/master/Fido.ps1).SubString(3)
```
_The reason I'm using `.SubString(3)` is because of the encoding of Fido.ps1 which has a byte order mark, if the encoding gets changed to UTF-8 it shouldn't be needed_

You can also pass arguments this way:
```powershell
$Script = (Invoke-RestMethod https://github.com/pbatard/Fido/raw/master/Fido.ps1).SubString(3)
iex "& {$Script} -Win 10"
```

**Comment by pbatard** [comment]
The reason why we need a BOM is mentioned in https://github.com/pbatard/Fido/blob/master/Fido.ps1#L21-L22.
Without it, the UI gets instantiated using a ISO-8859-1 codepage, and as such, we can't display Chinese or Japanese characters.

I'll also point out that FIDO's prime purpose is for Rufus usage, so I'm afraid I am never going to go out of my way for non-Rufus based usage. But your report may help other people, so thanks for sharing your findings.

I will close this issue now.

**Comment by rvdwegen** [comment]
Sorry for bumping this but wanted to add a oneliner,

`& $([scriptblock]::Create((New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/pbatard/Fido/master/Fido.ps1"))) -Win "Windows 11" -Ed "Pro" -Rel "22H2" -Lang "Int" -Arch "x64" -GetUrl`
