### ISSUE TITLE
Error: Could not parse languages

### ISSUE THREAD

**Issue by jespinoza84** [pbatard/Fido#38]
Receiving an "Error: could not parse languages" in both the UI and through PoSH. Happening for Win 10 and Win 11.

**Comment by luky92** [comment]
Try using a console mode

W dniu czw., 7.04.2022 o 19:49 James E ***@***.***>
napisał(a):

**Comment by pbatard** [comment]
I'm afraid I'm not seeing that error, so you're going to have to be way more specific about your environment and how exactly you invoke Fido.

Please don't assume that, if you see an error, everybody else will see it. Instead, you should always assume that the error you are seeing has something to do with your environment, and therefore, that you must provide as much information about it as you can, if you want to receive help.

At the very least, you should provide the __FULL__ output from your test, and not just the error.

For reference:
```
PS D:\Projects\Fido> .\Fido.ps1 -Win 11
No release specified (-Rel). Defaulting to '21H2 v1 (Build 22000.318 - 2021.11)'.
No edition specified (-Ed). Defaulting to 'Windows 11 Home/Pro/Edu'.
No language specified (-Lang). Defaulting to 'English International'.
No architecture specified (-Arch). Defaulting to 'x64'.
Selected: Windows 11 21H2 v1 (Build 22000.318 - 2021.11), Home/Pro/Edu, English International, [x64]
Downloading 'Win11_EnglishInternational_x64v1.iso' (5.0 GB)...
```

**Comment by pbatard** [comment]
Closing on account that OP did not provide enough details to allow replicating the issue.
