### ISSUE TITLE
Add the ability to download Windows Insider + Server vNext

### ISSUE THREAD

**Issue by Danik2343** [pbatard/Fido#43]
Add the ability to download Windows Insider + Server vNext

**Comment by pbatard** [comment]
This has been asked before.

Unlike the retail Windows ISO downloads, which __anybody can access__, these downloads require logging to the Microsoft servers before you can obtain a download link, which means that users must have an individual Insider or whatever account first.

I am not planning to propose any downloads in Fido that are not accessible without logging to Microsoft's servers, therefore I will reject this request.
