### ISSUE TITLE
Can't retrieve architectures from server

### ISSUE THREAD

**Issue by 512yottabytes** [pbatard/Fido#49]
Hello.
I've an error using Fido v=1.36 when I try to download Windows 11 & Windows 10.
`Can't retrieve architectures from server`
Windows 7 can still be downloaded.

**UPD:** I'm  **not in russia**. I do not use VPN. I'm not trying to download russian version of Windows.

**Comment by pbatard** [comment]
Network issue on your end or filtering from Microsoft's servers.

This is not a FIDO script issue. If it was, this issue tracker would be flooded with reports such as yours, which is clearly isn't.
