### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by mimimass16** [pbatard/Fido#57]
hi how to fix that
![Screenshot_2](https://user-images.githubusercontent.com/61828574/217091062-f4ac8c56-5dfe-43ef-8fca-9e134e2f5ba7.png)
![Screenshot_1](https://user-images.githubusercontent.com/61828574/217091063-92749e0b-9eec-4000-95ad-9dddd392f565.png)

**Comment by pineapple63** [comment]
Microsoft may have temporarily banned your IP address from downloading ISOs

if that is the case, wait at least 24 hours before trying again

**Comment by pbatard** [comment]
Answered [in the Rufus FAQ](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO).
