### ISSUE TITLE
Feature Request - Expected File Hashes

### ISSUE THREAD

**Issue by tigerguppy** [pbatard/Fido#59]
Fido is a great script as it makes downloading legitimate Windows OS ISOs so much easier via PowerShell, however there is no way to verify the expected file is fully and accurately downloaded. It would be helpful if there was a way to get the expected hash (preferably SHA256 as this is what is provided on https://www.microsoft.com/en-us/software-download/windows10ISO) of the ISO so it can be compared against the actual hash after the file is downloaded to ensure the file was fully and correctly downloaded.

**Comment by pbatard** [comment]
Yes, I know the hashes are provided. But I'm not planning to do anything with those in Fido just yet, as you need to understand that Fido is designed first and foremost to be used with Rufus (not as a standalone script) and that if I ever were to do anything with the hashes in Fido, it would be to feed their value to Rufus and not add a SHA validation in the script itself.
