### ISSUE TITLE
ERROR : New Update Rufus Cant Download/Request ISO from 8.1,10,11 New Update please Help!

### ISSUE THREAD

**Issue by LordVanhz** [pbatard/Fido#61]
![for report](https://user-images.githubusercontent.com/127580229/224465647-315835bd-776f-4d12-aff0-7c6762a51c49.png)

**Comment by pineapple63** [comment]
Its possible your IP address may have been temporarily banned from downloading ISOs, if this is the case, you will need to wait 24 hours before trying again

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO.
