### ISSUE TITLE
Error: Could not parse languages

### ISSUE THREAD

**Issue by MaxstarPCW** [pbatard/Fido#66]
Hi,

I receive this error when using this script. Also on different machines, one with en_US as default language and another one with nl-NL as default language. 

`PS C:\WINDOWS\system32> cd $home                                                                                        PS C:\Users\Gebruiker> sl desktop
PS C:\Users\Gebruiker\desktop> PowerShell.exe -ExecutionPolicy Bypass -File .\fido.ps1
Please Wait...
Querying https://www.microsoft.com/en-US/software-download/
Querying https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,windows11&query=&action=getskuinformationbyproductedition&sessionId=e74363f0-b9db-4ca3-837c-887b0aa954ac&productEditionId=2370&sdVersion=2
Error: Could not parse languages`

Screenshot: https://i.postimg.cc/sDs5GR14/fido-error.png

**Comment by farag2** [comment]
Hi @MaxstarPCW. There's no need at all to call powershell.exe from powershell.exe :cat:. Just run script `& "path_to_fido.ps1"`.
To change execution policy pemanently run

```powershell
Set-ExecutionPolicy -ExecutionPolicy Bypass -Force
```

to do it temporarily

```powershell
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
```

**Comment by pbatard** [comment]
I'm afraid I can't replicate this issue.

Also, you don't appear to be running the latest Fido script because there should be a line `Querying https://vlscppe.microsoft.com/tags?org_id=y6jn8c31&session_id=<GUID>` that is missing from your output, which is most likely your issue.

Please make sure you ALWAYS run the latest version of the script. Earlier versions are not supported.

**Comment by Maki079** [comment]
Hi!
i encountered the same issue today. It seems it appears while executing script form Windows Server 2022 machines. I tested on Windows 10 client and all worked fine for me. 

Regardless just letting you know how to replicate this issue.

**Comment by ave9858** [comment]
![image](https://github.com/pbatard/Fido/assets/112294121/031c4bf4-cd15-4919-baa6-64921c367535)
Works fine for me, idk how running on server vs client could even change the response returned by the server anyway

**Comment by pbatard** [comment]
> Regardless just letting you know how to replicate this issue.

Yeah, I'm not gonna go through a server install just to test this issue especially when other folks who tested on Server don't see it.

The reason why the whole script is Open Source is so that people who experience some issue can debug it and then try to propose a patch.
