### ISSUE TITLE
Windows 10 22H2 download is broken

### ISSUE THREAD

**Issue by ave9858** [pbatard/Fido#72]
It has been replaced with 22H2 v1, product ID 2618. An updated Home China has not yet been released, the current release is still working.

**Comment by pbatard** [comment]
Interesting. I **did** check yesterday before I pushed the 22H2 v2 update for Windows 11 whether there was also an update to Windows 10 22H2 and there was none then. So I concluded that there would be no 22H2 refresh for Windows 10.

Gotta wonder what was the point of removing the H1 releases when Microsoft is essentially still producing H1 releases...
