### ISSUE TITLE
Only latest release

### ISSUE THREAD

**Issue by ChrisRfr** [pbatard/Fido#74]
Hello,
Currently, only the latest release, version of Windows 10 or Windows 11 is available via the GUI or cmd line. 

```
PS > Fido.ps1 -win 10 -Rel List
Please select a Windows Release (-Rel) for Windows 10 (or use 'Latest' for most recent):
 - 22H2 v1 (Build 19045.2965 - 2023.05)
PS > Fido.ps1 -win 10 -Rel 20H1
Invalid Windows release provided.
Use '-Rel List' for a list of available Windows 10 releases or '-Rel Latest' for latest.
```
Is there any way to access older releases ?

**Comment by pbatard** [comment]
Nope. See #67.

You can try https://tb.rg-adguard.net/public.php or https://uupdump.net/known.php to generate rather than download older releases as Microsoft will no longer provide them as ISOs (and Fido does rely on ISOs that's provided by Microsoft).
