### ISSUE TITLE
Improved README.md - Mention Domain for ISO Download

### ISSUE THREAD

**Issue by hl2guide** [pbatard/Fido#75]
Please update `README.md` to mention that:

Users may need to whitelist the domain `vlscppe.microsoft.com`, depending on your network configuration.
If blocked the error shows as:
```
Error: The requested name is valid, but no data of the requested type was found. (vlscppe.microsoft.com:443)
```

**Comment by pbatard** [comment]
I think the error is pretty explicit, and since the script can change at any moment and new domain requests added/removed, I'm not planning to hold the hand of people whose networks have nonstandard configurations.
