### ISSUE TITLE
Error while trying to download a Windows 10 ISO

### ISSUE THREAD

**Issue by GabubuAvailable** [pbatard/Fido#78]
> Error: We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leveraging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this problem in error, please try again. If the problem persists you may contact Microsoft Support – Contact Us page for assistance. Refer to message code 715-123130 and XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.

This shows when I tried to download a copy of Windows 10 English International .iso with Rufus.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO
