### ISSUE TITLE
One more reason for someone to avoid mct

### ISSUE THREAD

**Issue by pitsi** [pbatard/Fido#79]
Yesterday, I came across this article from neowin.

Microsoft launched Windows 11 23H2, but Media Creation Tool still downloads 22H2
https://www.neowin.net/news/microsoft-launched-windows-11-23h2-but-media-creation-tool-still-downloads-22h2/

Can you please add this to the readme as one more reason to avoid mct? 
Thank you in advance.

p.s. Due to a minor health issue I have, I have not tested it myself yet.

**Comment by pbatard** [comment]
I don't think I want to do that, because the MCT does tend to download recent patches, and the goal of Fido is not to compete with MCT, but make retail ISOs easily accessible without jumping through hoops.

**Comment by ave9858** [comment]
This is only a minor issue since 23H2 is only a small enablement package, not a full build upgrade. The installed system can update quickly to 23H2 from 22H2. It is also possible for the enblement package to be added along with the other patches, but I'm not sure if the MCT will do this.

**Comment by pineapple63** [comment]
As far as I know, the Media Creation tool doesn't add any updates/patches that increase the build number
(At least with the 2 ISOs ive been using (both from the media creation tool, one from May 2023, the other from less than 24 hours ago as i write this), there is no difference in the build number)
So i don't think the media creation tool can add enablement packages (and even if you tried to add it manually, it wouldn't work due to the build being too old)

**Comment by pineapple63** [comment]
I think I now understand why the media creation tool wasn't updated when 23H2 was released
The most recent version of it (which does now download 23H2) produces an install.esd that is over 4GB in size

**Comment by pitsi** [comment]
I think the esd files got a bit bigger for 23h2. I can not confirm it right now, I am afk and I will be back in Sunday afternoon, sorry. I will reply before that though if I can get a valid download url to one.

**Comment by ave9858** [comment]
> I think the esd files got a bit bigger for 23h2. I can not confirm it right now, I am afk and I will be back in Sunday afternoon, sorry. I will reply before that though if I can get a valid download url to one.

23H2 ESD links can be found [here](https://pastebin.com/raw/mX7TebxP). Each release of Windows has bigger ESD files, 23H2 is 4.3 GB while the last 22H2 release is 3.7 GB

**Comment by pitsi** [comment]
Thank you for testing it for me :)
```
$ wget --spider http://dl.delivery.mp.microsoft.com/filestreamingservice/files/5e4998f9-7b26-42b4-b3a0-99c42f81b391/22631.2861.231204-0538.23H2_NI_RELEASE_SVC_REFRESH_CLIENTCONSUMER_RET_x64FRE_el-gr.esd 
Spider mode enabled. Check if remote file exists.
--2023-12-17 15:00:55--  http://dl.delivery.mp.microsoft.com/filestreamingservice/files/5e4998f9-7b26-42b4-b3a0-99c42f81b391/22631.2861.231204-0538.23H2_NI_RELEASE_SVC_REFRESH_CLIENTCONSUMER_RET_x64FRE_el-gr.esd
Resolving dl.delivery.mp.microsoft.com (dl.delivery.mp.microsoft.com)... 2a02:582:a00::d4cd:7e29, 2a02:582:a00::d4cd:7e70, 212.205.77.147, ...
Connecting to dl.delivery.mp.microsoft.com (dl.delivery.mp.microsoft.com)|2a02:582:a00::d4cd:7e29|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4758913459 (4.4G) [application/octet-stream]
Remote file exists.
```
