### ISSUE TITLE
Microsoft Error

### ISSUE THREAD

**Issue by meredpat000** [pbatard/Fido#81]
Suddenly receiving the following error when running the script: 

Error: We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leve
raging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this prob
lem in error, please try again. If the problem persists you may contact Microsoft Support – Contact Us page for assistance. Refer to message code 715-12
3130 and b7d66803-9c1d-4256-a051-d8fcfb1a7f8d.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO
