### ISSUE TITLE
Not downloading or getting URL

### ISSUE THREAD

**Issue by marcusheX** [pbatard/Fido#85]
Hello! When running Fido.ps1 the script functions appropriately until after selecting an edition to download, and it just endlessly hangs. The -GetUrl or standard download options simply hang after it correctly finds a version for Windows 10 or 11. Ideas? Thank you!

**Comment by lennvilardi** [comment]
+1

**Comment by marcusheX** [comment]
I believe this _may_ have to do with running Fido on a machine that:

A) Officially incompatible with Windows 10 or 11 but may be running it anyway
B) The Windows 10 or 11 version running is the same one being asked to download

My PC is running Windows 11 by unofficial patch and is not officially supported by Windows 11

I also received the `The underlying connection was closed: An unexpected error occurred on a send.` error one time after multiple tries. However deploying the script in the environment is working great on other older Windows 10 machines.

**Comment by pbatard** [comment]
Not seeing any issue. The problem is with your environment:
```
PS D:\Projects\Fido> .\Fido.ps1 -Win 10 -Rel Latest -GetUrl
https://software.download.prss.microsoft.com/dbazure/Win10_22H2_EnglishInternational_x64v1.iso?t=8a73baa1-0ffc-43e0-8832-7998f70a2bed&e=1704034820&h=4898612c71b480f614d1a23f8f5d34fab709d54a95f37e7f6680ea4a9a881e22
```
