### ISSUE TITLE
Fido is stuck 

### ISSUE THREAD

**Issue by Joeym0180** [pbatard/Fido#88]
Hi, 
When running Fido.ps1 the script is getting stuck at the locale query. 

```powershell
PS C:\Scripts> . .\Fido.ps1 -Win 11 -Verbose
No release specified (-Rel). Defaulting to '23H2 v2 (Build 22631.2861 - 2023.12)'.
No edition specified (-Ed). Defaulting to 'Windows 11 Home/Pro/Edu'.
Querying https://vlscppe.microsoft.com/tags?org_id=y6jn8c31&session_id=ff56121f-d0f5-4bb0-bc47-50aa72b2da4c
Querying https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,windows11&query=&action=getskuinformationbyproductedition&sessionId=ff56121f-d0f5-4bb0-bc47-50aa72b2da4c&productEditionId=2935&sdVersion=2

```
when starting with gui options:
```powershell
PS C:\Scripts> . .\Fido.ps1
```
and clicking continue on Windows 11 its stuck immediately 
![image](https://github.com/pbatard/Fido/assets/55741366/90b469d5-269e-409e-a832-18fb38647092)

We have tried different machines with different network connections. also tested it in Rufus 4.4 and is also not working.  

 it worked fine yesterday.

Hope to have an update soon! :)

**Comment by pbatard** [comment]
Thanks for reporting. I can replicate the issue. It seems Microsoft have once again changed something on their servers to make it more unfriendly to scripts.

I believe I have found a workaround however, and this is a good opportunity to add timeouts to our web requests, so, hopefully, the version of Fido that closes this request should address the issue.

**Comment by pbatard** [comment]
Just a note that I have force pushed a new update, because the previous workaround missing some elements.
