### ISSUE TITLE
version 1.55 appears broken

### ISSUE THREAD

**Issue by MxMaster3** [pbatard/Fido#90]
Very handy little tool but version 1.55 gets stuck on querying the MS download server.

**Comment by pbatard** [comment]
I'm not observing this, and neither are the thousands of people who use the script in Rufus (else they would report it).

From [similar issues](https://github.com/pbatard/rufus/issues?q=querying+download) reported for Rufus, you most likely have a security solution that is blocking access to some of the Microsoft servers, and you will have to address this on your side.
