### ISSUE TITLE
[Request] add param to set iso download path

### ISSUE THREAD

**Issue by MyDrift-user** [pbatard/Fido#92]
Hello yall

How about adding a parameter to the script that let's the user also define the path where he will find the ISO?

This would help a lot with automation and general management of the ISOs.

**Comment by pbatard** [comment]
I'm sorry but this looks like an issue that you would like somebody else to resolve for your specific workflow. I don't really see many people needing the feature you request.

If you have a specific workflow need, you should clone the project and edit the script yourself to make it work within your constraints.

Please bear in mind that I am designing the script almost exclusively for Rufus usage. I did add some non Rufus related features, but I have no plans to make Fido become the swiss army knife of Windows ISO downloads.

&rarr; Rejected

**Comment by MyDrift-user** [comment]
No Issues, thanks for the Feedback
