### ISSUE TITLE
unable to download image error

### ISSUE THREAD

**Issue by Linztric801** [pbatard/Fido#93]
Grabbing ISO URL                                                                                                        Running c:\temp\331-2408193748\fido.ps1 -Lang 'German' -Win 11 -Rel 23H2 -Ed Pro -GetUrl                                Error: We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leveraging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this problem in error, please try again. If the problem persists you may contact Microsoft Support â€“ Contact Us page for assistance. Refer to message code 715-123130 and 5cba0a21-c76d-4a44-9d37-e1b374360438.                                                                                                Downloading OS ISO

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO

**Comment by Linztric801** [comment]
thx
