### ISSUE TITLE
Add Windows 11 IoT Enterprise LTSC

### ISSUE THREAD

**Issue by kubo6472** [pbatard/Fido#94]
Is it possible to add Windows 11 IoT Enterprise LTSC, please?

![image](https://github.com/user-attachments/assets/d37282c7-7c51-40cf-81ef-9b28d0f77907)

A registration form needs to be filled.

Sample download links I got:
[AMD64](https://go.microsoft.com/fwlink/?linkid=2270353&clcid=0x409&culture=en-us&country=us)
If I download it, it goes from [this URL](https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso)
[ARM64](https://go.microsoft.com/fwlink/?linkid=2269595&clcid=0x409&culture=en-us&country=us)
And this is being downloaded from [this URL](https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_A64FRE_en-us.iso)

**Comment by pbatard** [comment]
> Is it possible to add Windows 11 IoT Enterprise LTSC, please?

No it's not, because, as you found out:

> A registration form needs to be filled.

Also see https://github.com/pbatard/Fido?tab=readme-ov-file#additional-notes that **explicitly** says LTSC will **NOT** be added to FIDO.

**Comment by ave9858** [comment]
Those are also EVAL ISOs, which have an expiration date and should never be used for production systems
