### ISSUE TITLE
running script manually

### ISSUE THREAD

**Issue by Vistaking** [pbatard/Fido#95]
Running this .\fido.ps1 -Win 11 -ed Pro -Lang English inside powershell as an administrator I get this Error 

No release specified (-Rel). Defaulting to '24H2 (Build 26100.1742 - 2024.10)'.
Error: Cannot convert value "–" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte."

**Comment by pbatard** [comment]
Not seeing any issue on my side:
```
PS D:\Projects\Fido> .\fido.ps1 -Win 11 -ed Pro -Lang English
No release specified (-Rel). Defaulting to '24H2 (Build 26100.1742 - 2024.10)'.
No architecture specified (-Arch). Defaulting to 'x64'.
Selected: Windows 11 24H2 (Build 26100.1742 - 2024.10), Home/Pro/Edu, English, [x64]
Downloading 'Win11_24H2_English_x64.iso' (5.0 GB)...     
```

Tested with both default PS (5.1) and PS 7.4.5.

The problem therefore appears to be with your specific environment.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO
