### ISSUE TITLE
Error: We are unable to complete your request at this time / Code 715-123130" when using the ISO download feature

### ISSUE THREAD

**Issue by tvongsaly4592** [pbatard/Fido#99]
As happened in the past (https://github.com/pbatard/rufus/issues/2130) it appears that Microsoft have once again altered their ISO download service to make it more difficult for third party applications to use them.

As a result, you will be getting the following error:
![Screenshot_1](https://github.com/user-attachments/assets/edbe3ae2-3790-4e2f-b3e9-5af15d9dfe84)

Why does this keep happening to the Rufus app while downloading ISOs?!

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO
